### ISSUE TITLE
Stuck in "Generating"

### ISSUE THREAD

**Issue by eniac111** [thomas-maurice/PEMetrator#1]
Congratulations for the project. I was doing something similar but for web server user certs and then I noticed this. 

The problem is that the certificate requests are stuck in "Generating". Maybe Celery isn't working? I don't see anything in the logs.

**Comment by thomas-maurice** [comment]
Hey, thanks for submitting an issue

Can I have more input on how you deployed and run the soft ?

Also I do not maintain it for a quite long amount of time so I cannot guarantee I'll fix the issue in a decent time ;)

**Comment by eniac111** [comment]
Hello Thomas,

Thank you for the fast reply. I'm using fresh Ubuntu 16.06 container with Redis. The Python packages are installed with pip and requirements.txt.

I'm not expecting a fix from you. Just, if you remember something, give me a direction :)

Cheers!

**Comment by eniac111** [comment]
The problem was caused by a wrong SMTP configuration.
